### ISSUE TITLE
Setting zoom factor to .01 in Tiberium_Alliances_Zoom.user.js

### ISSUE THREAD

**Issue by XDaast** [ffi82/CnC-TA#1]
Is there an easy way to set the zoom factor to .01 other than the scroll wheel?

**Comment by ffi82** [comment]
ClientLib.Vis.VisMain.GetInstance().get_Region().set_ZoomFactor(.01);

yes... have to wait for load though before grabbing object data.

this returns true or false if area is loaded:
ClientLib.Vis.VisMain.GetInstance().get_Region().get_VisAreaComplete()

and another "issue" with the get_VisAreaComplete()
it shows 'false' with zoom .01... it is too much i think.

made this helper function for this issue:
```
// Calculate ZoomFactor for your window width and height. The bigger ZoomFactor is chosen to ensure the map fills the window and crops off whatever doesn't fit... get_VisAreaComplete() will return 'false' otherwise.
function calculateZoomFactor() {
    const region = ClientLib.Vis.VisMain.GetInstance().get_Region();
    const fullMapWidth = region.get_MaxXPosition(); // 102400
    const fullMapHeight = region.get_MaxYPosition(); // 76800
    const viewableWidth = window.innerWidth;
    const viewableHeight = window.innerHeight;
    const zoomFactorWidth = Math.ceil(viewableWidth / fullMapWidth * 1000) / 1000;
    const zoomFactorHeight = Math.ceil(viewableHeight / fullMapHeight * 1000) / 1000;
    return Math.max(zoomFactorWidth, zoomFactorHeight);
}

//and call:
ClientLib.Vis.VisMain.GetInstance().get_Region().set_ZoomFactor(calculateZoomFactor());
```
________________________________
From: XDaast ***@***.***>
Sent: Tuesday, November 19, 2024 9:51 PM
To: ffi82/CnC-TA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ffi82/CnC-TA] Setting zoom factor to .01 in Tiberium_Alliances_Zoom.user.js (Issue #1)


Is there an easy way to set the zoom factor to .01 other than the scroll wheel?

**Comment by ffi82** [comment]
and another "issue" with the get_VisAreaComplete()
it shows "false" with zoom .01... it is too much i think.

made this helper function for this issue:

// Calculate ZoomFactor for your window width and height. The bigger ZoomFactor is chosen to ensure the map fills the window and crops off whatever doesn't fit... get_VisAreaComplete() will return 'false' otherwise.
function calculateZoomFactor() {
    const fullMapWidth = region.get_MaxXPosition(); // 102400
    const fullMapHeight = region.get_MaxYPosition(); // 76800
    const viewableWidth = window.innerWidth;
    const viewableHeight = window.innerHeight;
    const zoomFactorWidth = Math.ceil(viewableWidth / fullMapWidth * 1000) / 1000;
    const zoomFactorHeight = Math.ceil(viewableHeight / fullMapHeight * 1000) / 1000;
    return Math.max(zoomFactorWidth, zoomFactorHeight);
}

and call:
ClientLib.Vis.VisMain.GetInstance().get_Region().set_ZoomFactor(calculateZoomFactor());

________________________________

**Comment by XDaast** [comment]
Thank you!
